Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"

  ## config de la VM db-server
  config.vm.define "db-server" do |db_config|
    db_config.vm.hostname = "db-server"
    db_config.vm.network "private_network", ip: "192.168.56.11"
    db_config.vm.synced_folder ".", "/vagrant"
    db_config.vm.provision "shell", inline: <<-SHELL
      chmod +x /vagrant/db_server/db_server_provision.sh
    SHELL
    db_config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end

  ## config de la VM web-server
  config.vm.define "web-server" do |web_config|
    web_config.vm.hostname = "web-server"
    web_config.vm.network "private_network", ip: "192.168.56.10"
    web_config.vm.network "forwarded_port", guest: 80, host: 8080
    web_config.vm.synced_folder ".", "/vagrant"
    web_config.vm.synced_folder "./shared", "/var/www/html",
      owner: "www-data",
      group: "www-data"
    web_config.vm.provision "shell", inline: <<-SHELL
      chmod +x /vagrant/web-server/web_server_provision.sh
    SHELL
    web_config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end
end   
    ##### Options  #########################################################################################################    
    # config.vm.hdd = "20GB" --> si non instancié, espace dynamique gérer par le provider
    ##Taille maximale du disque - nécessite VBoxManage via vb.customize
    # vb.customize ['modifyhd', :id, '--resize', 20480]
    ##Activer l'accélération 3D (intéressant pour certains usages GUI)
    # vb.customize ['modifyvm', :id, '--accelerate3d', 'on']
    ## force le démarrage en mode GUI
    # vb.gui = true
    ## détruit l’état sauvegardé d’une VM à chaque arrêt (comme une « machine rebootant proprement à neuf »)
    # vb.customize ['modifyvm', :id, '--discardstate', 'on']
    ########################################################################################################################
