Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10" # Use Debian 10 base box
  config.vm.box_version = "4.3.12" # Specify the box version

  config.vm.network "private_network", ip: "192.168.56.10" # Set a private network IP

  config.vm.provider "virtualbox" do |vb| # Customize VirtualBox settings
    vb.memory = "2048" # Allocate 2GB of RAM
    vb.cpus = 2 # Allocate 2 CPUs
  end
end


    
   